[package]
name = "guessing-game"
version = "0.1.0"
authors = ["Felipe Marino <felipemarino91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"